INSERT INTO permissions (code, name, module, action)
VALUES
('dashboard.view','View Dashboard','dashboard','view'),
('hotel.view','View Hotels','hotel','view'),
('hotel.create','Create Hotel','hotel','create'),
('hotel.update','Update Hotel','hotel','update'),
('branch.view','View Branches','branch','view'),
('branch.create','Create Branch','branch','create'),
('branch.update','Update Branch','branch','update'),
('branch.delete','Delete Branch','branch','delete'),
('user.view','View Users','user','view'),
('user.create','Create User','user','create'),
('user.update','Update User','user','update'),
('user.delete','Delete User','user','delete'),
('role.view','View Roles','role','view'),
('role.create','Create Role','role','create'),
('role.update','Update Role','role','update'),
('permission.assign','Assign Permissions','permission','assign'),
('room.view','View Rooms','room','view'),
('room.create','Create Room','room','create'),
('room.update','Update Room','room','update'),
('booking.view','View Bookings','booking','view'),
('booking.create','Create Booking','booking','create'),
('booking.update','Update Booking','booking','update'),
('booking.cancel','Cancel Booking','booking','cancel'),
('checkin.create','Check In','checkin','create'),
('checkout.create','Check Out','checkout','create'),
('payment.view','View Payments','payment','view'),
('payment.create','Create Payment','payment','create'),
('housekeeping.view','View Housekeeping','housekeeping','view'),
('housekeeping.update','Update Housekeeping','housekeeping','update'),
('maintenance.view','View Maintenance','maintenance','view'),
('maintenance.update','Update Maintenance','maintenance','update'),
('expense.view','View Expenses','expense','view'),
('expense.create','Create Expense','expense','create'),
('report.view','View Reports','report','view'),
('report.export','Export Reports','report','export'),
('audit_log.view','View Audit Logs','audit_log','view')
ON CONFLICT (code) DO NOTHING;
